---
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/array-type": 2
  "@typescript-eslint/ban-ts-comment":
    - 2
    - ts-ignore: allow-with-description
  "@typescript-eslint/ban-types": 0
  "@typescript-eslint/brace-style":
    - 2
    - 1tbs
    - allowSingleLine: true
  "@typescript-eslint/comma-dangle":
    - 2
    - always-multiline
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/indent":
    - 2
    - 2
  "@typescript-eslint/lines-between-class-members":
    - 2
    - never
    - exceptAfterSingleLine: true
  "@typescript-eslint/member-delimiter-style":
    - 2
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
  "@typescript-eslint/no-empty-function":
    - 2
    - allow:
        - getters
        - setters
        - constructors
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-extra-parens": 2
  "@typescript-eslint/no-extra-semi": 2
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/no-shadow": 1
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/object-curly-spacing":
    - 2
    - always
  "@typescript-eslint/prefer-as-const": 0
  "@typescript-eslint/quotes":
    - 2
    - single
  "@typescript-eslint/semi":
    - 2
    - always
    - omitLastInOneLineBlock: true
  "@typescript-eslint/space-before-function-paren":
    - 2
    - anonymous: never
      asyncArrow: always
      named: never
  array-bracket-spacing:
    - 2
    - never
  arrow-spacing:
    - 2
    - after: true
      before: true
  block-spacing:
    - 2
    - always
  brace-style: 0
  camelcase: 0
  comma-dangle: 0
  comma-spacing:
    - 2
    - after: true
      before: false
  dot-location:
    - 2
    - property
  eol-last: 2
  eqeqeq: 2
  indent: 0
  key-spacing:
    - 2
    - afterColon: true
      beforeColon: false
      mode: strict
  lines-between-class-members: 0
  no-empty:
    - 2
    - allowEmptyCatch: true
  no-empty-function: 0
  no-extra-parens: 0
  no-extra-semi: 0
  no-fallthrough: 0
  no-multi-spaces: 2
  no-multiple-empty-lines:
    - 2
    - max: 2
      maxBOF: 0
      maxEOF: 0
  no-shadow: 0
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-use-before-define: 0
  no-whitespace-before-property: 2
  object-curly-spacing: 0
  object-shorthand:
    - 2
    - always
  prefer-const: 0
  quotes: 0
  rest-spread-spacing:
    - 2
    - never
  semi: 0
  semi-spacing:
    - 2
    - after: true
      before: false
  space-before-blocks: 2
  space-before-function-paren: 0
  space-in-parens:
    - 2
    - never
  space-unary-ops:
    - 2
    - nonwords: false
      words: true
  spaced-comment:
    - 2
    - always
  template-curly-spacing:
    - 2
    - never
  wrap-iife:
    - 2
    - outside
    - functionPrototypeMethods: true
  yoda: 2
