---
env:
  node: true
root: true
extends:
  - "@chookslint/typescript"
parserOptions:
  project: ./tsconfig.json
rules:
  complexity: "off"
  new-cap: "off"
  operator-linebreak: "off"
  sort-imports: "off"
